config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: "users/sessions" }

  root 'blogs#index'

  resources :blogs do
    resource :favorite, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show] do
    get :favorites, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :users, through: :favorites

  is_impressionable counter_cache: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/draft.rb
class Draft < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :blogs
  has_many :favorites
  has_many :favorite_blogs, through: :favorites, source: :blog

  def like(blog)
    favorites.find_or_create_by(blog_id: blog.id)
  end

  def unlike(blog)
    favorite = faborites.find_by(blog_id: blog.id)
    favorite.destroy if favorite
  end

  def favorite_to?(blog)
    favorites.where(blog_id: blog.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user! 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blogs, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all.order("id DESC")
    @ranked_blogs = Blog.order('impressions_count DESC').limit(5)
    @test_blogs = Blog.order("id DESC").limit(5)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
  end

  def show
    impressionist(@blog, nil)
    # impressionist(@blog, nil, unique: [:session_hash])
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to user_path(current_user.id), notice: "ブログを更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @blog.destroy
      redirect_to user_path(current_user.id), notice: "ブログを削除しました"
    else
      render user_path(current_user.id)
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :overview, :text, :image).merge(user_id: current_user.id)
  end

  def set_blogs
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # after_action :move_to_root

  def create
    favorite = current_user.favorites.build(blog_id: params[:blog_id])
    favorite.save
    redirect_to root_path
  end

  def destroy
    favorite = Favorite.find_by(blog_id: params[:blog_id], user_id: current_user.id)
    favorite.destroy
    redirect_to root_path
  end

  # private
  # def move_to_root
  #   redirect_to :root_path and return
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super
  end

  # def edit
  #   super
  # end

  # def update
  #   super
  # end

  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def favorite
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-card">
  <%= link_to "", blog_path(blog.id), class: "blog-card__link" %>
  <div class="blog-card__image">
    <%= image_tag(blog.image)%>
  </div>
  <div class="blog-card__contents">
    <div class="blog-card__contents__title">
      <span><%= blog.title %></span>
    </div>
    <div class="blog-card__contents__overview">
      <p><%= blog.overview %></p>
    </div>
    <div class="blog-card__contents__info">
      <%= render partial: "favorites/favorites", locals: { blog: blog } %>
      <div class="blog-card__contents__info__name">
        <%= link_to "@#{blog.user.name}", user_path(blog.user_id) %>
      </div>
      <div class="blog-card__contents__info__date">
        <%= blog.created_at.to_s(:date) %>
      </div> 
    </div>
  </div>
</div>

app/views/blogs/_ranking.html.erb
<div class="ranking__blog">
  <%= link_to "", blog_path(blog.id), class: "ranking__blog__link" %>
  <div class="ranking__blog__left">
    <%= image_tag(blog.image)%>
  </div>
  <div class="ranking__blog__right">
    <%= blog.title %>
  </div>
</div>

app/views/blogs/_side-contents.html.erb
<div class="side-contents">
  <div class="ranking">人気記事ランキング
    <div class="ranking__tab">
      <button class="ranking__tab__btn select">週間</button>
      <button class="ranking__tab__btn">月間</button>
      <button class="ranking__tab__btn">年間</button>
    </div>
    <div class="ranking__wrapper">
      <div class="ranking__blogs ranking__blogs--week show">
        <%= render partial: "ranking", collection: @ranked_blogs, as: "blog" %>
      </div>
      <div class="ranking__blogs ranking__blogs--month">
        <%= render partial: "ranking", collection: @test_blogs, as: "blog" %>
      </div>
      <div class="ranking__blogs ranking__blogs--year">
        <%= render partial: "ranking", collection: @ranked_blogs, as: "blog" %>
      </div>
    <div>
  </div>
</div>

app/views/blogs/create.html.erb
<p>投稿が完了しました！</p>
<%= link_to "投稿フォームへ戻る", "/blogs/new" %>

app/views/blogs/edit.html.erb
<div class="blog-form">
  <h1>ブログ投稿</h1>
  <%= form_for @blog do |f| %>
    <div class="blog-form__field blog-form__field__title">
      <%= f.text_field :title, placeholder: "タイトルを入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__overview">
      <%= f.text_field :overview, placeholder: "サブタイトルや記事の概要を入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__text">
      <%= f.text_area :text, cols: "80", rows: "20", placeholder: "記事の内容を自由にお書き下さい", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__image">
      <%= f.text_field :image, type: "text", placeholder: "写真のURLを入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field__footer">
      <%= f.submit "保存する", class: "blog-form__field__btn" %>
      <%= f.submit "投稿する", class: "blog-form__field__btn" %>
    </div>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="contents">
  <div class="blogs">
   <%= render @blogs %>
  </div>
  <%= render partial: "side-contents", locals: { blogs: @blogs } %>
</div>

app/views/blogs/new.html.erb
<div class="blog-form">
  <h1>ブログ投稿</h1>
  <%= form_for @blog do |f| %>
    <div class="blog-form__field blog-form__field__title">
      <%= f.text_field :title, placeholder: "タイトルを入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__overview">
      <%= f.text_field :overview, placeholder: "サブタイトルや記事の概要を入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__text">
      <%= f.text_area :text, cols: "80", rows: "20", placeholder: "記事の内容を自由にお書き下さい", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field blog-form__field__image">
      <%= f.text_field :image, type: "text", placeholder: "写真のURLを入力してください", class: "blog-form__field__input" %>
    </div>
    <div class="blog-form__field__footer">
      <%= f.submit "保存する", class: "blog-form__field__btn" %>
      <%= f.submit "投稿する", class: "blog-form__field__btn" %>
    </div>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="blog-wrapper">
  <div class="blog-container">
    <div class="blog">
      <h1 class="blog__title">
        <%= @blog.title %>
      </h1>
      <div class="blog__info">
        <%= render partial: "favorites/favorites", locals: { blog: @blog } %>
        <div class="blog__info__author">
          <%= link_to "@#{@blog.user.name}", user_path(@blog.user_id) %>
        </div>
        <div class="blog__info__date">
          <%= "#{@blog.created_at.to_s(:datetime)} 投稿" %>
        </div>
      </div>
      <h2 class="blog__overview">
        <%= @blog.overview %>  
      </h2>
      <div class="blog__text">
        <%= @blog.text %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<div class="blog-card__contents__info__favorite">
  <% if user_signed_in? %>
    <% if blog.favorited_by?(current_user) %>
      <%= link_to blog_favorite_path(blog.id), method: :delete do %>
        <%= fas_icon "star", class: "blog-card__contents__info__favorite__icon" %>
      <% end %>
    <% else %>
      <%= link_to blog_favorite_path(blog.id), method: :post do %>
        <%= far_icon "star", class: "blog-card__contents__info__favorite__icon" %>
      <% end %>
    <% end %>
  <% else %>
    <%= far_icon "star", class: "blog-card__contents__info__favorite__icon" %>
  <% end %>
  <%= blog.favorites.count %>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Blog App", root_path, class: "brand-logo" %>
    <ul id="nav-menus" class="nav-menus">
    <% if user_signed_in?%>
      <li class="nav-menu"><%= link_to "新規投稿", new_blog_path, class: "nav-menu__btn" %></li>
      <li class="nav-menu"><%= link_to "マイページ", user_path(current_user.id), class: "nav-menu__btn" %></li>
      <li class="nav-menu"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-menu__btn" %></li>
    <% else %>
      <li class="nav-menu"><%= link_to "ログイン", new_user_session_path, class: "nav-menu__btn" %></li>
      <li class="nav-menu"><%= link_to "新規登録", new_user_registration_path, class: "nav-menu__btn" %></li>
    <% end %>
      <li class="nav-menu"><%= link_to "検索", root_path, class: "nav-menu__btn" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/notifications" %>
    <%= render partial: "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn"%><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="blogs">
  <% @user.blogs.each do |blog| %>
    <div class="mypage-blogs">
      <%= render partial: "blogs/blog", locals: { blog: blog } %>
      <% if @user.id == current_user.id %>
        <div class="mypage-blogs__footer">
          <div class="mypage-blogs__footer__btn mypage-blogs__footer__edit">
            <%= link_to "編集", edit_blog_path(blog) %>
          </div>
          <div class="mypage-blogs__footer__btn mypage-blogs__footer__delete">
            <%= link_to "削除", blog_path(blog), method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>